"""Export Panel — generates AGENTS.md and/or Cursor .mdc rule files."""
from __future__ import annotations

from pathlib import Path

from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import (
    QComboBox, QHBoxLayout, QLabel, QMessageBox,
    QPlainTextEdit, QPushButton, QVBoxLayout, QWidget,
)
from gui.i18n import tr


def _banner(text: str, color: str = "#F5F0FF", border: str = "#7C3AED") -> QLabel:
    lbl = QLabel(text)
    lbl.setWordWrap(True)
    lbl.setTextFormat(Qt.TextFormat.RichText)
    lbl.setStyleSheet(
        f"background:{color}; border-left:4px solid {border};"
        " border-radius:3px; padding:6px 10px;"
        " color:#333; font-size:11px; margin-bottom:4px;"
    )
    return lbl


# ── renderers ─────────────────────────────────────────────────────────────────

def _render_agents_md(agents, skills_store, hooks_store) -> str:
    """Generate top-level AGENTS.md for GitHub Copilot."""
    lines = [
        "# AI Agents\n\n",
        "> Auto-generated by Agent Manager.\n\n",
    ]
    for agent in agents:
        lines.append(f"## {agent.name}\n\n")
        if agent.role:
            lines.append(f"**Role:** {agent.role}  \n")
        if agent.model:
            lines.append(f"**Model:** {agent.model}  \n")
        if agent.description:
            lines.append(f"\n{agent.description}\n")
        skill_names = [
            s.name for sid in agent.skill_ids
            if (s := skills_store.get(sid)) is not None
        ]
        if skill_names:
            lines.append(f"\n**Skills:** {', '.join(skill_names)}\n")
        if getattr(agent, "hard_rules", []):
            lines.append("\n**Hard rules:**\n")
            for rule in agent.hard_rules:
                lines.append(f"- {rule}\n")
        lines.append("\n---\n\n")
    return "".join(lines)


def _render_cursor_mdc(agent, skills_store) -> str:
    """Generate .cursor/rules/<id>.mdc content for Cursor IDE."""
    desc  = (agent.description or f"You are {agent.name}.").replace("\n", " ")[:200]
    lines = [
        "---\n",
        f"description: {desc}\n",
        "globs: \n",
        "alwaysApply: false\n",
        "---\n\n",
        f"# {agent.name}\n\n",
    ]
    if agent.role:
        lines.append(f"You are a **{agent.role}**.\n\n")
    if agent.description:
        lines.append(f"{agent.description}\n\n")
    if getattr(agent, "hard_rules", []):
        lines.append("## Hard Rules\n\n")
        for rule in agent.hard_rules:
            lines.append(f"- {rule}\n")
        lines.append("\n")
    if agent.skill_ids:
        lines.append("## Skills\n\n")
        for sid in agent.skill_ids:
            skill = skills_store.get(sid)
            if not skill:
                continue
            phase = getattr(skill.phase, "value", str(skill.phase)) if getattr(skill, "phase", None) else "general"
            phase_tag = f" _{phase}_" if phase != "general" else ""
            lines.append(f"### {skill.name}{phase_tag}\n\n")
            if skill.when_to_use:
                lines.append(f"**When to use:** {skill.when_to_use}\n\n")
            if skill.steps:
                for i, step in enumerate(skill.steps, 1):
                    lines.append(f"{i}. {step}\n")
                lines.append("\n")
            ec = getattr(skill, "exit_criteria", "")
            if ec:
                lines.append(f"**Exit criteria:** {ec}\n\n")
            anti = getattr(skill, "anti_rationalizations", [])
            if anti:
                lines.append("**Anti-rationalizations:**\n")
                for item in anti:
                    lines.append(f"- {item}\n")
                lines.append("\n")
    return "".join(lines)


# ── panel ─────────────────────────────────────────────────────────────────────

class ExportPanel(QWidget):
    """Tab for exporting agent config to AGENTS.md / Cursor .mdc files."""

    _FORMATS = ["AGENTS.md (Copilot)", "Cursor (.cursor/rules/)", "Oba formaty"]

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self._build_ui()

    def _build_ui(self) -> None:
        v = QVBoxLayout(self)
        v.setContentsMargins(8, 8, 8, 8)
        v.setSpacing(6)

        self._banner = _banner(
            tr("export.banner")
        )
        v.addWidget(self._banner)

        top = QHBoxLayout()
        self._lbl_agent = QLabel(tr("export.agent_lbl"))
        top.addWidget(self._lbl_agent)
        self.agent_combo = QComboBox()
        self.agent_combo.setMinimumWidth(180)
        self.agent_combo.currentIndexChanged.connect(self._on_preview)
        top.addWidget(self.agent_combo)

        self._lbl_fmt = QLabel(tr("export.fmt_lbl"))
        top.addWidget(self._lbl_fmt)
        self.format_combo = QComboBox()
        self.format_combo.addItems(self._FORMATS)
        self.format_combo.currentIndexChanged.connect(self._on_preview)
        top.addWidget(self.format_combo)

        refresh_btn = QPushButton("⟳")
        refresh_btn.setFixedWidth(28)
        refresh_btn.setToolTip("Odśwież listę agentów")
        refresh_btn.clicked.connect(self._refresh)
        top.addWidget(refresh_btn)
        top.addStretch()
        v.addLayout(top)

        self.preview_edit = QPlainTextEdit()
        self.preview_edit.setReadOnly(True)
        self.preview_edit.setStyleSheet(
            "font-family:Consolas,monospace; font-size:12px; background:#FAFAFA;"
        )
        v.addWidget(self.preview_edit)

        btn_row = QHBoxLayout()
        self.export_btn = QPushButton(tr("btn.export"))
        self.export_btn.setFixedHeight(32)
        self.export_btn.setStyleSheet(
            "QPushButton { background:#7C3AED; color:white; border-radius:4px; padding:4px 20px; }"
            "QPushButton:hover { background:#6D28D9; }"
        )
        self.export_btn.clicked.connect(self._on_export)
        btn_row.addStretch()
        btn_row.addWidget(self.export_btn)
        v.addLayout(btn_row)

        self._refresh()

    def _refresh(self) -> None:
        self.agent_combo.blockSignals(True)
        self.agent_combo.clear()
        self.agent_combo.addItem(tr("export.all"), userData=None)
        try:
            from gui.state import get_registry
            for agent in get_registry().agents.list():
                self.agent_combo.addItem(agent.name, userData=agent.id)
        except Exception:
            pass
        self.agent_combo.blockSignals(False)
        self._on_preview()

    def _get_agents_and_reg(self):
        from gui.state import get_registry
        reg      = get_registry()
        agent_id = self.agent_combo.currentData()
        if agent_id is None:
            return reg.agents.list(), reg
        agent = reg.agents.get(agent_id)
        return ([agent] if agent else []), reg

    def _build_preview(self) -> str:
        fmt = self.format_combo.currentText()
        try:
            agents, reg = self._get_agents_and_reg()
            if not agents:
                return "(brak agentów w rejestrze)"
            if fmt.startswith("AGENTS.md"):
                return _render_agents_md(agents, reg.skills, reg.hooks)
            if fmt.startswith("Cursor"):
                parts = []
                for agent in agents:
                    parts.append(f"# ===== {agent.id}.mdc =====\n\n")
                    parts.append(_render_cursor_mdc(agent, reg.skills))
                    parts.append("\n")
                return "".join(parts)
            # Oba formaty
            md  = _render_agents_md(agents, reg.skills, reg.hooks)
            cur = []
            for agent in agents:
                cur.append(f"# ===== {agent.id}.mdc =====\n\n")
                cur.append(_render_cursor_mdc(agent, reg.skills))
                cur.append("\n")
            return md + "\n\n---\n\n# CURSOR FORMAT\n\n" + "".join(cur)
        except Exception as exc:
            return f"(błąd generowania podglądu: {exc})"

    def _on_preview(self) -> None:
        self.preview_edit.setPlainText(self._build_preview())

    def _on_export(self) -> None:
        fmt = self.format_combo.currentText()
        try:
            agents, reg = self._get_agents_and_reg()
            if not agents:
                QMessageBox.information(self, "Brak agentów", "Brak agentów do eksportu.")
                return

            from gui.state import get_workspace
            ws   = get_workspace()
            saved: list[str] = []

            if fmt.startswith("AGENTS.md") or fmt.startswith("Oba"):
                content = _render_agents_md(agents, reg.skills, reg.hooks)
                path    = ws / "AGENTS.md"
                path.write_text(content, encoding="utf-8")
                saved.append(str(path))

            if fmt.startswith("Cursor") or fmt.startswith("Oba"):
                rules_dir = ws / ".cursor" / "rules"
                rules_dir.mkdir(parents=True, exist_ok=True)
                for agent in agents:
                    content = _render_cursor_mdc(agent, reg.skills)
                    out     = rules_dir / f"{agent.id}.mdc"
                    out.write_text(content, encoding="utf-8")
                    saved.append(str(out))

            QMessageBox.information(
                self, "Zapisano",
                "Wyeksportowano:\n" + "\n".join(saved)
            )
        except Exception as exc:
            QMessageBox.critical(self, "Błąd eksportu", str(exc))

    def retranslate_ui(self) -> None:
        self._lbl_agent.setText(tr("export.agent_lbl"))
        self._lbl_fmt.setText(tr("export.fmt_lbl"))
        self.export_btn.setText(tr("btn.export"))
        # Refresh "all agents" item text in combo
        if self.agent_combo.count() > 0:
            self.agent_combo.setItemText(0, tr("export.all"))
        self._banner.setText(tr("export.banner"))
